---
- hosts: flaskapp_node
  become: yes
  vars:
    APP_NAME: ExampleApp
    REPO_URL: https://github.com/WiktorKarnia/CeneoScraper-Python
    APP_PORT: 8080
  tasks:
    - name: "install os packages"
      yum:
        name: python3, python3-pip, git
    - name: "sync repo"
      git:
        repo: "{{REPO_URL}}"
        dest: "/opt/{{APP_NAME}}"
        force: yes
    - name: "app user"
      user:
        name: "{{ APP_NAME }}"
    - name: "change permissions"
      file:
        owner: "{{APP_NAME}}"
        group: "{{APP_NAME}}"
        path: "/opt/{{APP_NAME}}"
        recurse: yes
    - name: "venv for python + requirements"
      pip:
        requirements: "/opt/{{APP_NAME}}/requirements.txt"
        virtualenv: "/opt/{{APP_NAME}}/.venv"
        virtualenv_command: python3 -m venv
      become_user: "{{ APP_NAME }}"
    - name: "register as a service"
      template:
        src: files/app.service
        dest: "/etc/systemd/system/{{APP_NAME}}.service"
    - name: "start service"
      systemd:
        daemon_reload: yes 
        name: "{{ APP_NAME }}"
        state: restarted
- hosts: load_balancer
  become: yes
  vars:
    app_ips:
      - 172.31.28.223:8080
  tasks:
    - name: install epel
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: install nginx
      yum:
        name: nginx
        state: present
    - name: put nginx conf
      template:
        src: files/lb.conf
        dest: /etc/nginx/conf.d/blog.conf
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded


  